'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { TommyzkiButton as TommyzkiButtonElement, defineCustomElement as defineTommyzkiButton } from "@tommyzki/ui-core/dist/components/tommyzki-button.js";
import React from 'react';

export type TommyzkiButtonEvents = NonNullable<unknown>;

export const TommyzkiButton: StencilReactComponent<TommyzkiButtonElement, TommyzkiButtonEvents> = /*@__PURE__*/ createComponent<TommyzkiButtonElement, TommyzkiButtonEvents>({
    tagName: 'tommyzki-button',
    elementClass: TommyzkiButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as TommyzkiButtonEvents,
    defineCustomElement: defineTommyzkiButton
});
