/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TommyzkiButton {
        "label": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTommyzkiButtonElement extends Components.TommyzkiButton, HTMLStencilElement {
    }
    var HTMLTommyzkiButtonElement: {
        prototype: HTMLTommyzkiButtonElement;
        new (): HTMLTommyzkiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "tommyzki-button": HTMLTommyzkiButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TommyzkiButton {
        "label"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "tommyzki-button": TommyzkiButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "tommyzki-button": LocalJSX.TommyzkiButton & JSXBase.HTMLAttributes<HTMLTommyzkiButtonElement>;
        }
    }
}
