/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TommyzkiButton {
        "disabled": boolean;
        "fullwidth": boolean;
        "loading": boolean;
        "rounded": boolean;
        "size": 'sm' | 'md' | 'lg';
        "variant": 'primary' | 'secondary' | 'danger' | 'outline' | 'ghost' | 'link';
    }
}
declare global {
    interface HTMLTommyzkiButtonElement extends Components.TommyzkiButton, HTMLStencilElement {
    }
    var HTMLTommyzkiButtonElement: {
        prototype: HTMLTommyzkiButtonElement;
        new (): HTMLTommyzkiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "tommyzki-button": HTMLTommyzkiButtonElement;
    }
}
declare namespace LocalJSX {
    interface TommyzkiButton {
        "disabled"?: boolean;
        "fullwidth"?: boolean;
        "loading"?: boolean;
        "rounded"?: boolean;
        "size"?: 'sm' | 'md' | 'lg';
        "variant"?: 'primary' | 'secondary' | 'danger' | 'outline' | 'ghost' | 'link';
    }
    interface IntrinsicElements {
        "tommyzki-button": TommyzkiButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tommyzki-button": LocalJSX.TommyzkiButton & JSXBase.HTMLAttributes<HTMLTommyzkiButtonElement>;
        }
    }
}
